### ISSUE TITLE
RPEC test inconsistent

### ISSUE THREAD

**Issue by kosmicowboy** [learn-co-curriculum/sinatra-mvc-file-structure#13]
application_controller_spec.rb

should read something like 

```
it 'can change dog age' do
  @dog = Dog.new("rudolph", "mastiff", 2)
  @dog.age = 3
  expect(@dog.age).to eq(3)
end
```

currently reads

```
it 'can change dog age' do
  @dog = Dog.new("rudolph", "mastiff", 2)
  @dog. name = "bessie"
  expect(@dog.name).to eq("bessie")
end
```

**Comment by kosmicowboy** [comment]
I'm not sure if the name or age attribute is intended to be writeable, but the test name doesn't match the actual test

**Comment by AnnJohn** [comment]
thanks @kylegraydev; we'll look into this

**Comment by pletcher** [comment]
Fixed in https://github.com/ruchiramani/sinatra-mvc-file-structure/commit/824b49820c8e7b33e9db3326ab63dfea4eeab203
