### ISSUE TITLE
rake (loadError) - Is this an error from my environment or part of the lesson to solve?

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/sinatra-mvc-file-structure#15]
I honestly don't know if this is my fault but this works when I require 'rake' in my gemfile.  I did run bundle install before issuing these commands.  Is this a problem with my ruby environment setup?  

[12:38:31](master) activerecord-associations-intro
♥ rspec --fail-fast
/Users/yonk/Development/code/foo/activerecord-associations-intro/config/environment.rb:5:in `require': cannot load such file -- rake (LoadError)
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/config/environment.rb:5:in`<top (required)>'
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/spec/spec_helper.rb:3:in `require_relative'
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/spec/spec_helper.rb:3:in`<top (required)>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in `require'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in`block in requires='
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in `each'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in`requires='
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:108:in`each'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:21:in`configure'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:101:in `setup'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:88:in`run'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:73:in `run'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:41:in`invoke'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/exe/rspec:4:in `<top (required)>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in`load'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`eval'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
[12:39:37](master) activerecord-associations-intro

♥ bundle exec rspec --fail-fast
/Users/yonk/Development/code/foo/activerecord-associations-intro/config/environment.rb:5:in `require': cannot load such file -- rake (LoadError)
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/config/environment.rb:5:in`<top (required)>'
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/spec/spec_helper.rb:3:in `require_relative'
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/spec/spec_helper.rb:3:in`<top (required)>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in `require'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in`block in requires='
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in `each'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in`requires='
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:108:in`each'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:21:in`configure'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:101:in `setup'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:88:in`run'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:73:in `run'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:41:in`invoke'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/exe/rspec:4:in `<top (required)>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in`load'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`eval'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
[12:39:45](master) activerecord-associations-intro

/Users/yonk/Development/code/foo/activerecord-associations-intro/config/environment.rb:5:in `require': cannot load such file -- rake (LoadError)
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/config/environment.rb:5:in`<top (required)>'
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/spec/spec_helper.rb:3:in `require_relative'
    from /Users/yonk/Development/code/foo/activerecord-associations-intro/spec/spec_helper.rb:3:in`<top (required)>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in `require'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in`block in requires='
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in `each'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1280:in`requires='
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:108:in`each'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration_options.rb:21:in`configure'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:101:in `setup'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:88:in`run'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:73:in `run'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:41:in`invoke'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.3.0/exe/rspec:4:in `<top (required)>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in`load'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`eval'
    from /Users/yonk/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

♥ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]
[12:39:51](master) activerecord-associations-intro
♥ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
[12:39:56](master) activerecord-associations-intro
♥

**Comment by genericlady** [comment]
after requiring 'rake' in the gemfile i can run my tests.  no bundle install necessary.  rf is an alias for rspec --fail-fast

[12:45:38](master) activerecord-associations-intro
♥ rf

Song
  has a name (FAILED - 1)

Failures:

  1) Song has a name
     Failure/Error: @song = Song.create(name: "Forever")
     ActiveRecord::StatementInvalid:
       Could not find table 'songs'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:511:in `table_structure'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:385:in`columns'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/attributes.rb:93:in`columns'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/attributes.rb:98:in `columns_hash'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/inheritance.rb:205:in`subclass_from_attributes?'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/inheritance.rb:54:in `new'
     # /Users/yonk/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.2/lib/active_record/persistence.rb:33:in`create'
     # ./spec/models/01_song_spec.rb:3:in `block (2 levels) in <top (required)>'

Finished in 0.00398 seconds (files took 0.71141 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/models/01_song_spec.rb:10 # Song has a name

[12:46:15](master) activerecord-associations-intro

**Comment by PeterBell** [comment]
Hi @genericlady thanks so much for submitting this feedback on the curriculum - very much appreciated!  Can't replicate the error. I just clone, `bundle` and then `rspec --fail-fast` and get the appropriate list of failing tests. Going to task @aturkewi to be a second pair of eyes just in case it only works for me, but if it works for him I'll ask him to close this out and we'll see if we get any more reports of issues.

**Comment by genericlady** [comment]
ok I thought it might be a problem on my end.  thank you.
