### ISSUE TITLE
Dogs tests not hinted at or explained at all in the README.md

### ISSUE THREAD

**Issue by gnfisher** [learn-co-curriculum/sinatra-mvc-file-structure#17]
So this lab is really quite confusing. I created a Dog class as a model that inherited from `model.rb`... assuming that's what they were looking for... anyway I got the tests to pass, and when I looked at the solution code after submitting I saw that they created an `@dog` instance var to pass to the erb file from `ApplicationController`... but this is a poorly designed lesson. I have a little background in rails and MVC pattern so I figured they were looking for a model (though there is no test nor hint that they want to create an instance to pass to the view here)... some better wording is needed to explain this random request for a simple Dog class... at least a hint that it should be a model or something. I can imagine a lot of students being totally lost on this, or creating code that passes but doesn't necessarily serve the purpose of introducing the idea of passing data from a model to controller to view...

**Comment by AnnJohn** [comment]
thanks @gnfisher for this great feedback. We're going to be updating our sinatra content within the next few weeks so will revisit this when we get to that point.

**Comment by mendelB** [comment]
@AnnJohn The solution branch seems to be an older version of the lab where the student had to fill in more code. The Master seems to have been sort of drastically updated, should the solution branch be changed to reflect that?

**Comment by AnnJohn** [comment]
hi @mendelB yes, the solution branch should be changed to reflect that. thanks!
