### ISSUE TITLE
DOG?

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/sinatra-mvc-file-structure#21]
Not sure what the point of this `DOG` constant is –– it doesn't ever seem to be invoked. Perhaps a relic from a past version of the lab?

https://github.com/learn-co-curriculum/sinatra-mvc-file-structure/blob/master/spec/controllers/application_controller_spec.rb#L6-L8

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by gj** [comment]
Also, it raises this error in 5/6 tests in the `Dog class` test section:

``` bash
/Users/Hobbes/dev/code/sinatra-mvc-file-structure-v-000/spec/controllers/application_controller_spec.rb:7: warning: already initialized constant DOG
/Users/Hobbes/dev/code/sinatra-mvc-file-structure-v-000/spec/controllers/application_controller_spec.rb:7: warning: previous definition of DOG was here
```

The errors disappear when the test file `before` block containing `DOG` is commented out.
