### ISSUE TITLE
Verify accuracy of Gemfile.lock description

### ISSUE THREAD

**Issue by wlycdgr** [learn-co-curriculum/sinatra-mvc-file-structure#25]
The lesson text offers this explanation for the Gemfile.lock file: "The lock word is actually because it makes sure that only one thing is running bundle install at a time." This comes across as incorrect/misleading given that the purpose of the lock file is to document and enforce a specific working gem versions configuration.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We corrected the `Gemfile.lock` definition.

Aas always thank you for contributing.
