### ISSUE TITLE
There's a test missing in the spec/controllers/application_controller_spec.rb file.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sinatra-mvc-file-structure#29]
Hi. This lesson is really good, but I noticed that there was a test missing. There should be a test that checks for whether you can change the dog's breed. Something like this:

```
describe ApplicationController do
  describe 'Dog class' do
    ...
    # Maybe put this between the tests that check for changing the dog's name and age:
    it 'can change dog breed' do
      @dog = Dog.new("rudolph", "mastiff", 2)
      @dog.breed = "beagle"
      expect(@dog.breed).to eq("beagle")
    end
    ...
  end
end
```

Thanks as always for looking into this!

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback!
We have updated the materials and believe your issue to have been resolved.
