### ISSUE TITLE
Include Sample App Code

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/sinatra-mvc-file-structure#3]
This repo includes code for a very basic sample app.

The README works entirely without that code. However, in theory, it'd be nice if this README included a working sample app and referenced it's source code within the README. We'd have to instruct the student to clone the lab and play and explore the local files as they go through the README.

**Comment by jmburges** [comment]
I agree. They don't know views yet, so just write the erb for them. But have them create a model (cats, dogs, whatever) and then create a route in the controller and then finally connect up the model to the view
