### ISSUE TITLE
a little unclear

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sinatra-mvc-file-structure#6]
so let me disclaim this by saying that most people finished with lab without a problem but some were really hung up. there are no instructions, is purely test-driven which is fine but they've only see the whole "set an instance variable in the controller and render it in a view" thing once or twice and i don't _think_ it was every discussed explicitly (i could be wrong!). So would be good to provide some basic instructions/a reminder about that instance variable -> view set-up.

**Comment by AnnJohn** [comment]
@vicfriedman can you take a look at this one when you're back? thanks

**Comment by victhevenot** [comment]
just spoke with @SophieDeBenedetto and closing this issue.
