### ISSUE TITLE
Tests issue and file name extension issue 

### ISSUE THREAD

**Issue by deniznida** [learn-co-curriculum/sinatra-mvc-file-structure#9]
Last test in spec requires 'breed' to be 'dalmation' (it is hard-coded this way) so students will always have to instantiate a Dog class with the breed set to 'dalmation.' Otherwise test will fail. 
- Solution is to remove hard-coded breed 'dalmation'

View file extension should be index.html.erb and not index.erb

**Comment by victhevenot** [comment]
Hey @deniznida - I'm not sure what version of the lab you're looking at, but we removed the dalmatian reference because students haven't learned views in sinatra yet.

Also, in Sinatra you don't use the `.html` file extension, you can check out the docs on Sinatra templating languages [here](http://www.sinatrarb.com/intro.html#Erb%20Templates)

Im going to go ahead and close this!

**Comment by deniznida** [comment]
@vicfriedman you are right about the .html, the only issue with that is we show our students always .html.erb where we also should tell them that the .html is not necessary in Sinatra. 

when I opened this issue the dalmatian reference was still there... 

Thanks for looking into this...

**Comment by victhevenot** [comment]
hey @deniznida 

the readme specially addresses the `.html` issue: 

```
views directory

This directory holds the code that will be displayed in the browser. In a Sinatra app we use .erb files instead of .html files because .erb files allow us to include regular, old HTML tags AND special erb tags which contain Ruby code. We can name them anything we like, but by convention, our file names will match up with the action that renders them. For example, a GET request to / typically renders a file called index.erb.
```

can you take at the version of the lab your or your students are using about dalmations? I want to make sure all is resolved!

**Comment by deniznida** [comment]
@vicfriedman my classes repo looks good now. We deployed this lab definitely after you fixed the specs. I don't know what happened but its all good now. Thanks

**Comment by victhevenot** [comment]
awesome! thanks @deniznida
